version: "3.7"
services:
  database:
    build: 
      context: ./database
    restart: always
    environment:
      POSTGRES_DB: incident-management
    ports: 
      - '5432:5432'
    volumes:
      - db_volume:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - '4000:4000'
    depends_on:
      - database

  front-end:
    build: 
      context: ./front-end
    ports:
      - 3000:3000
    stdin_open: true
    depends_on:
      - database
      - backend

volumes: 
  db_volume: